# .gitlab-ci.yml

variables:
  IMAGE_NAME: savemeter/savemeter-api
  REGISTRY: registry.gitlab.com

# Define the stages of the pipeline
stages:
  - build

# Define the job to build the Docker image
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - IMAGE_TAG=$CI_COMMIT_TAG # Set IMAGE_TAG to the Git tag name
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG . # Use IMAGE_TAG as the image tag
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
  - tags