# .gitlab-ci.yml

variables:
  IMAGE_NAME: savemeter/savemeter-api
  REGISTRY: registry.gitlab.com

# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define the job to build the Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - IMAGE_TAG=$CI_COMMIT_TAG # Set IMAGE_TAG to the Git tag name
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t latest . # Use IMAGE_TAG as the image tag
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
    - tags

deploy_image:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl $AZURE_WEBHOOK -H "" -d ""
  only:
    - tags
