version: '3'

services:
  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    volumes:
      - seq-data:/data

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
  seq-data:
    driver: local