// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SaveMeter_Services_Finances_Infrastructure
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"BankName")]
            public string BankName { get; set; }

            [ColumnName(@"Categories")]
            public string Categories { get; set; }

            [ColumnName(@"CategoryId")]
            public string CategoryId { get; set; }

            [ColumnName(@"CreatedAt")]
            public string CreatedAt { get; set; }

            [ColumnName(@"Customer")]
            public string Customer { get; set; }

            [ColumnName(@"Description")]
            public string Description { get; set; }

            [ColumnName(@"SkipAnalysis")]
            public string SkipAnalysis { get; set; }

            [ColumnName(@"TransactionDate")]
            public string TransactionDate { get; set; }

            [ColumnName(@"UpdatedAt")]
            public string UpdatedAt { get; set; }

            [ColumnName(@"Value")]
            public string Value { get; set; }

            [ColumnName(@"_id")]
            public string __id { get; set; }

            [ColumnName(@"_t")]
            public string __t { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"BankName")]
            public string BankName { get; set; }

            [ColumnName(@"Categories")]
            public string Categories { get; set; }

            [ColumnName(@"CategoryId")]
            public uint CategoryId { get; set; }

            [ColumnName(@"CreatedAt")]
            public string CreatedAt { get; set; }

            [ColumnName(@"Customer")]
            public float[] Customer { get; set; }

            [ColumnName(@"Description")]
            public float[] Description { get; set; }

            [ColumnName(@"SkipAnalysis")]
            public string SkipAnalysis { get; set; }

            [ColumnName(@"TransactionDate")]
            public string TransactionDate { get; set; }

            [ColumnName(@"UpdatedAt")]
            public string UpdatedAt { get; set; }

            [ColumnName(@"Value")]
            public float[] Value { get; set; }

            [ColumnName(@"_id")]
            public string __id { get; set; }

            [ColumnName(@"_t")]
            public string __t { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
